### ISSUE TITLE
Open3d bug

### ISSUE THREAD

**Issue by WH0226** [anthonyzhou-1/ldm_pdes#1]
Hello, I have torch 2.0.0 and open3d 0.18.0 installed in my environment, but I encountered the following error when setting use_open3d=True:

RuntimeError:
BuildSpatialHashTable was not compiled with CUDA support

**Comment by anthonyzhou-1** [comment]
I can't reproduce this so I'm not entirely sure what could be happening; do you know if you have installed pytorch-scatter or pytorch with CUDA support? Otherwise you could try use_open3d=False (if you can afford the memory/runtime). I know the dependencies are a little annoying so I apologize that I cannot be of more help.
